// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js loads .env.local natively, but the Prisma CLI does not: plain
// `dotenv/config` reads only `.env`, which this project does not have. That
// left DATABASE_URL undefined for every CLI command — `prisma migrate status`,
// `migrate deploy`, `studio` and `db seed` all failed with "The datasource.url
// property is required in your Prisma config file", which reads like a config
// bug rather than a missing env file.
// .env.local is loaded first and wins, matching Next.js's own precedence.
// dotenv never overwrites a variable that is already set, so a real environment
// variable (Vercel, CI) still takes precedence over both files.
loadEnv({ path: ".env.local" });
loadEnv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
